spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://3.137.216.242:5432/bd-erp
    username: postgres
    password: System*2020
  jpa:
    show-sql: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        