package com.ti.erpws.publica.model.response;
// Generated 17/04/2019 11:20:35 AM by Hibernate Tools 4.3.1


import com.ti.erpws.publica.entity.PubTipdoc;
//import lombok.Data;


/**
 * PubTipdoc generated by hbm2java
 */

public class PubTipdocVO {

    private Long idPubTipdoc;
    private String tipdoc;
    private String nombre;
    private String codsunat;
    private Character comprobantedepago;
    private Character estado;
    private Short saldo;
    private Character aplicadoc;
    private String tipoasiento;
    private String tipper;
    private Character syscaj;
    private Character syspro;
    private Character sysproTipreg;
    private Character sysproApldoc;
    private Character sysproTipimp;
    private String etiqueta;
    private Integer fAlmacen;
    private String sysvtas;
    private Integer pdbSerdocMaxlong;
    private Integer pdbNumdocMaxlong;
    private Integer pdbFlagFormulario;
    private String expReguNumdoc;
    private String expReguSerdoc;
    private Character pleSignoSerdoc;
    private String pleSerdocLong;
    private Character pleSignoNumdoc;
    private String pleNumdocLong;
    private Character pleVenNulo;
    private Character pleComNulo;
    private Character pleDiaNulo;
    private String mensajeErrorNumdoc;
    private String mensajeErrorSerdoc;
    private String utilizadoEnOc;
    private Character reqValidacion;
    private Integer indDetraccion;
    private String abreviatura;
    private Character sysLiqServ;
    private Character aplicaret;

    public PubTipdocVO() {
    }
    
    public PubTipdocVO(PubTipdoc data) {
    	
        this.idPubTipdoc = data.getIdPubTipdoc();
        this.tipdoc = data.getTipdoc();
        this.nombre = data.getNombre();
        this.codsunat = data.getCodsunat();
        this.comprobantedepago = data.getComprobantedepago();
        this.estado = data.getEstado();
        this.saldo = data.getSaldo();
        this.aplicadoc = data.getAplicadoc();
        this.tipoasiento = data.getTipoasiento();
        this.tipper = data.getTipper();
        this.syscaj = data.getSyscaj();
        this.syspro = data.getSyspro();
        this.sysproTipreg = data.getSysproTipreg();
        this.sysproApldoc = data.getSysproApldoc();
        this.sysproTipimp = data.getSysproTipimp();
        this.etiqueta = data.getEtiqueta();
        this.fAlmacen = data.getFAlmacen();
        this.sysvtas = data.getSysvtas();
        this.pdbSerdocMaxlong = data.getPdbSerdocMaxlong();
        this.pdbNumdocMaxlong = data.getPdbNumdocMaxlong();
        this.pdbFlagFormulario = data.getPdbFlagFormulario();
        this.expReguNumdoc = data.getExpReguNumdoc();
        this.expReguSerdoc = data.getExpReguSerdoc();
        this.pleSignoSerdoc = data.getPleSignoSerdoc();
        this.pleSerdocLong = data.getPleSerdocLong();
        this.pleSignoNumdoc = data.getPleSignoNumdoc();
        this.pleNumdocLong = data.getPleNumdocLong();
        this.pleVenNulo = data.getPleVenNulo();
        this.pleComNulo = data.getPleComNulo();
        this.pleDiaNulo = data.getPleDiaNulo();
        this.mensajeErrorNumdoc = data.getMensajeErrorNumdoc();
        this.mensajeErrorSerdoc = data.getMensajeErrorSerdoc();
        this.utilizadoEnOc = data.getUtilizadoEnOc();
        this.reqValidacion = data.getReqValidacion();
        this.indDetraccion = data.getIndDetraccion();
        this.abreviatura = data.getAbreviatura();
        this.sysLiqServ = data.getSysLiqServ();
        this.aplicaret = data.getAplicaret();
    	
    }

    public Long getIdPubTipdoc() {
        return idPubTipdoc;
    }

    public void setIdPubTipdoc(Long idPubTipdoc) {
        this.idPubTipdoc = idPubTipdoc;
    }

    public String getTipdoc() {
        return tipdoc;
    }

    public void setTipdoc(String tipdoc) {
        this.tipdoc = tipdoc;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getCodsunat() {
        return codsunat;
    }

    public void setCodsunat(String codsunat) {
        this.codsunat = codsunat;
    }

    public Character getComprobantedepago() {
        return comprobantedepago;
    }

    public void setComprobantedepago(Character comprobantedepago) {
        this.comprobantedepago = comprobantedepago;
    }

    public Character getEstado() {
        return estado;
    }

    public void setEstado(Character estado) {
        this.estado = estado;
    }

    public Short getSaldo() {
        return saldo;
    }

    public void setSaldo(Short saldo) {
        this.saldo = saldo;
    }

    public Character getAplicadoc() {
        return aplicadoc;
    }

    public void setAplicadoc(Character aplicadoc) {
        this.aplicadoc = aplicadoc;
    }

    public String getTipoasiento() {
        return tipoasiento;
    }

    public void setTipoasiento(String tipoasiento) {
        this.tipoasiento = tipoasiento;
    }

    public String getTipper() {
        return tipper;
    }

    public void setTipper(String tipper) {
        this.tipper = tipper;
    }

    public Character getSyscaj() {
        return syscaj;
    }

    public void setSyscaj(Character syscaj) {
        this.syscaj = syscaj;
    }

    public Character getSyspro() {
        return syspro;
    }

    public void setSyspro(Character syspro) {
        this.syspro = syspro;
    }

    public Character getSysproTipreg() {
        return sysproTipreg;
    }

    public void setSysproTipreg(Character sysproTipreg) {
        this.sysproTipreg = sysproTipreg;
    }

    public Character getSysproApldoc() {
        return sysproApldoc;
    }

    public void setSysproApldoc(Character sysproApldoc) {
        this.sysproApldoc = sysproApldoc;
    }

    public Character getSysproTipimp() {
        return sysproTipimp;
    }

    public void setSysproTipimp(Character sysproTipimp) {
        this.sysproTipimp = sysproTipimp;
    }

    public String getEtiqueta() {
        return etiqueta;
    }

    public void setEtiqueta(String etiqueta) {
        this.etiqueta = etiqueta;
    }

    public Integer getfAlmacen() {
        return fAlmacen;
    }

    public void setfAlmacen(Integer fAlmacen) {
        this.fAlmacen = fAlmacen;
    }

    public String getSysvtas() {
        return sysvtas;
    }

    public void setSysvtas(String sysvtas) {
        this.sysvtas = sysvtas;
    }

    public Integer getPdbSerdocMaxlong() {
        return pdbSerdocMaxlong;
    }

    public void setPdbSerdocMaxlong(Integer pdbSerdocMaxlong) {
        this.pdbSerdocMaxlong = pdbSerdocMaxlong;
    }

    public Integer getPdbNumdocMaxlong() {
        return pdbNumdocMaxlong;
    }

    public void setPdbNumdocMaxlong(Integer pdbNumdocMaxlong) {
        this.pdbNumdocMaxlong = pdbNumdocMaxlong;
    }

    public Integer getPdbFlagFormulario() {
        return pdbFlagFormulario;
    }

    public void setPdbFlagFormulario(Integer pdbFlagFormulario) {
        this.pdbFlagFormulario = pdbFlagFormulario;
    }

    public String getExpReguNumdoc() {
        return expReguNumdoc;
    }

    public void setExpReguNumdoc(String expReguNumdoc) {
        this.expReguNumdoc = expReguNumdoc;
    }

    public String getExpReguSerdoc() {
        return expReguSerdoc;
    }

    public void setExpReguSerdoc(String expReguSerdoc) {
        this.expReguSerdoc = expReguSerdoc;
    }

    public Character getPleSignoSerdoc() {
        return pleSignoSerdoc;
    }

    public void setPleSignoSerdoc(Character pleSignoSerdoc) {
        this.pleSignoSerdoc = pleSignoSerdoc;
    }

    public String getPleSerdocLong() {
        return pleSerdocLong;
    }

    public void setPleSerdocLong(String pleSerdocLong) {
        this.pleSerdocLong = pleSerdocLong;
    }

    public Character getPleSignoNumdoc() {
        return pleSignoNumdoc;
    }

    public void setPleSignoNumdoc(Character pleSignoNumdoc) {
        this.pleSignoNumdoc = pleSignoNumdoc;
    }

    public String getPleNumdocLong() {
        return pleNumdocLong;
    }

    public void setPleNumdocLong(String pleNumdocLong) {
        this.pleNumdocLong = pleNumdocLong;
    }

    public Character getPleVenNulo() {
        return pleVenNulo;
    }

    public void setPleVenNulo(Character pleVenNulo) {
        this.pleVenNulo = pleVenNulo;
    }

    public Character getPleComNulo() {
        return pleComNulo;
    }

    public void setPleComNulo(Character pleComNulo) {
        this.pleComNulo = pleComNulo;
    }

    public Character getPleDiaNulo() {
        return pleDiaNulo;
    }

    public void setPleDiaNulo(Character pleDiaNulo) {
        this.pleDiaNulo = pleDiaNulo;
    }

    public String getMensajeErrorNumdoc() {
        return mensajeErrorNumdoc;
    }

    public void setMensajeErrorNumdoc(String mensajeErrorNumdoc) {
        this.mensajeErrorNumdoc = mensajeErrorNumdoc;
    }

    public String getMensajeErrorSerdoc() {
        return mensajeErrorSerdoc;
    }

    public void setMensajeErrorSerdoc(String mensajeErrorSerdoc) {
        this.mensajeErrorSerdoc = mensajeErrorSerdoc;
    }

    public String getUtilizadoEnOc() {
        return utilizadoEnOc;
    }

    public void setUtilizadoEnOc(String utilizadoEnOc) {
        this.utilizadoEnOc = utilizadoEnOc;
    }

    public Character getReqValidacion() {
        return reqValidacion;
    }

    public void setReqValidacion(Character reqValidacion) {
        this.reqValidacion = reqValidacion;
    }

    public Integer getIndDetraccion() {
        return indDetraccion;
    }

    public void setIndDetraccion(Integer indDetraccion) {
        this.indDetraccion = indDetraccion;
    }

    public String getAbreviatura() {
        return abreviatura;
    }

    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }

    public Character getSysLiqServ() {
        return sysLiqServ;
    }

    public void setSysLiqServ(Character sysLiqServ) {
        this.sysLiqServ = sysLiqServ;
    }

    public Character getAplicaret() {
        return aplicaret;
    }

    public void setAplicaret(Character aplicaret) {
        this.aplicaret = aplicaret;
    }
}


